[tool.poetry]
name = "end-to-end-ml-project-with-ml-flow"
version = "0.1.0"
description = ""
authors = ["Tushar <tusharrohilla70@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
